services:
  - type: web
    name: terra-viva
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: DISABLE_DOCS
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: terra_viva_db
          property: connectionString

databases:
  - name: terra_viva_db
    databaseName: terra_viva
    user: terra_viva
    plan: free